@startuml
skinparam linetype poly
skinparam nodesep 100 /' horizontal separator '/
skinparam ranksep 50 /' vertical separator '/
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 1
skinparam titleBorderColor black
skinparam titleBackgroundColor AliceBlue
skinparam groupInheritance 1
scale 1
hide empty members
'hide circle'
skinparam titleFontSize 16
skinparam legendBackgroundColor AliceBlue

title PSC Filing API: Internal Data Model Class Structure
legend right
|=Revision |=Date |
|    0.1    |     22/11/2022    |
end legend

    package "model" {

        package "entity" {

            class Address {
                -addressLine1
                -addressLine2
                -careOf
                -country
                -poBox
                -postalCode
                -premises
                -region
            }

            class Date3Tuple {
                -day:int
                -month:int
                -year:int
            }
            note right of Date3Tuple
               day is null
               for partial DOB
            end note

            class Identification {
                -countryRegistered
                -legalAuthority
                -legalForm
                -placeRegistered
                -registrationNumber
            }

            class NameElements {
                -forename
                -otherForenames
                -surname
                -title
            }

            class Links {
                -self: URI
            }

            abstract class Psc {
                -address: Address
                -addressSameAsRegisteredOfficeAddress: Boolean
                -ceasedOn: LocalDate
                -createdAt: Instant
                -etag
                -identification
                -kind
                -links: Links
                -name
                -naturesOfControl[1..*]
                -notifiedOn: LocalDate
                -referenceEtag
                -referencePscId
                -referencePscListEtag
                -registerEntryDate: LocalDate
                -updatedAt: Instant
            }

           note left of Psc::naturesOfControl
                See public spec for full list
            end note

            class PscIndividual {
                -countryOfResidence
                -dateOfBirth: Date3Tuple
                -nameElements: NameElements
                -nationality
                -residentialAddress: Address
                -residentialAddressSameAsCorrespondenceAddress: Boolean
                -statementActionDate: LocalDate
                -statementType
            }

            class PscIdentified {
            }
           note "This models the RLE (corporate) and the \nORP (legal) types of PSC" as Note1
           Note1 ... PscIdentified

            class Statement {
                -actionDate: LocalDate
                -createdAt: Instant
                -kind
                -links: Links
                -referenceEtag
                -referenceStatementId
                -restrictionsNoticeWithdrawlReason
                -statement
                -updatedAt: Instant
            }


          note left of Statement::referenceStatementId
                Required for PSC09
           end note

          note left of Statement::statement
                See public spec for full list
           end note

           Identification -[hidden] PscIdentified

/'            Date3Tuple -[hidden] Address
           Links -[hidden] Statement
            PscIndividual -[hidden] PscIdentified

            together {
                class PscIndividual
                class PscIdentified
            }

            together {
                class Address
                class Date3Tuple
                class Identification
                class NameElements
            }'/

            Psc::address o-l- Address
            PscIndividual::residential_address o-- Address
            PscIndividual::dateOfBirth o-u- Date3Tuple
            PscIdentified o-u- Identification
            Psc::links o-u- Links
            Statement::links o-u- Links
            PscIndividual::nameElements o-u- NameElements
            Psc <|-- PscIndividual
            Psc <|-- PscIdentified
        }
    }


@enduml