@startuml

title PSC Filing API: Internal Data Model Class Structure

'skinparam style strictuml

legend right
|=Revision |=Date |
|    0.3    |     22/03/2023    |
end legend

    package "model" {

        package "entity" {

           class PscCommon {
             -address: Address
             -addressSameAsRegisteredOfficeAddress: Boolean
             -ceasedOn: LocalDate
             -createdAt: Instant
             -etag
             -identification
             -kind
             -links: Links
             -name
             -naturesOfControl[1..*]
             -notifiedOn: LocalDate
             -referenceEtag
             -referencePscId
             -registerEntryDate: LocalDate
             -updatedAt: Instant
           }

           class PscWithIdentificationFiling extends PscCommon {
             -identification: Identification
             -statementActionDate LocalDate
             -statementType
           }

           note "This models the corporate entity (RLE) and \nlegal person (ORP) types of PSC" as Note1
           PscWithIdentificationFiling .. Note1

           class PscIndividualFiling extends PscCommon {
                -countryOfResidence
                -nameElements: NameElements
                -nationality
                -residentialAddress: Address
                -residentialAddressSameAsCorrespondenceAddress: Boolean
                -dateOfBirth: Date3Tuple
                -statementActionDate: LocalDate
                -statementType
           }

            class Address {
                -addressLine1
                -addressLine2
                -careOf
                -country
                -locality
                -poBox
                -postalCode
                -premises
                -region
            }
    
            class Date3Tuple {
                -day:int {nullable}
                -month:int
                -year:int
            }

            class Identification {
                -countryRegistered
                -legalAuthority
                -legalForm
                -placeRegistered
                -registrationNumber
            }
   
            class NameElements {
                -forename
                -otherForenames
                -surname
                -title
            }
   
            class Statement {
                -actionDate: LocalDate
                -createdAt: Instant
                -kind
                -links: Links
                -referenceEtag
                -referenceStatementId
                -restrictionsNoticeWithdrawlReason
                -statement
                -updatedAt: Instant
            }

            class Links {
                -self: URI
                -validationStatus: URI
            }

         note left of Statement::referenceStatementId
                Required for PSC09
           end note

            NameElements -o PscIndividualFiling::nameElements
            Identification -o PscWithIdentificationFiling::identification
            PscCommon::address o- Address
            Links -o PscCommon::links
            Address --o PscIndividualFiling::residentialAddress
            PscIndividualFiling::dateOfBirth o-- Date3Tuple
            Statement::links o-- Links

           }
    }

@enduml