@startuml
'https://plantuml.com/class-diagram
'ortho/polyline
'skinparam linetype polyline
skinparam nodesep 50 /' horizontal separator '/
skinparam ranksep 100 /' vertical separator '/
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 1
skinparam titleBorderColor black
skinparam titleBackgroundColor AliceBlue
skinparam groupInheritance 1
skinparam legendBackgroundColor AliceBlue

'scale 800 width
scale 0.5
hide empty members
'hide circle'
skinparam titleFontSize 18

title PSC Filing API: Target Data Model Class Structure

legend right
|=Revision |=Date |
|    0.2    |     29/11/2022    |
endlegend

    package "model" {

        package "dto" {

            class AddressDto {
                -addressLine1
                -addressLine2
                -careOf
                -country
                -locality
                -poBox
                -postalCode
                -premises
                -region
            }

            class Date3TupleDto {
                -day:int {nullable}
                -month:int
                -year:int
            }

            class IdentificationDto {
                -countryRegistered
                -placeRegistered
                -registrationNumber
                -legalAuthority
               -legalForm
            }

            class NameElementsDto {
                -forename
                -otherForenames
                -surname
                -title
            }
            
            class PscStatementDto {
                -referenceEtag
                -referenceStatementId
                -restrictionsNoticeWithdrawlReason
                -statementActionDate: LocalDate
                -statementType
            }

            note "Required for PSC09" as Note2

          Note2 - PscStatementDto::referenceStatementId

/'          note left of PscStatementDto::statementType
                See public spec for full list
           end note'/

            interface PscCommon {
                +getAddress():  AddressDto
                +getAddressSameAsRegisteredOfficeAddres()s: Boolean
                +getCeasedOn(): LocalDate
                +getNaturesOfControl(): String[]
                +getNotifiedOn(): LocalDate
                +getReferenceEtag()
                +getReferencePscId()
                +getRegisterEntryDate(): LocalDate
            }

            class PscCommonDto implements PscCommon {
                -address: AddressDto
                -addressSameAsRegisteredOfficeAddress: Boolean
                -ceasedOn: LocalDate
                -naturesOfControl[1..*]
                -notifiedOn: LocalDate
                -referenceEtag
                -referencePscId
                -registerEntryDate: LocalDate
            }

/'           note left of PscCommonDto::naturesOfControl
                See public spec for full list
            end note'/

            class PscIndividualDto implements PscCommon {
                -pscCommon: PscCommonDto
                -countryOfResidence
                -dateOfBirth: Date3TupleDto
                -nationality
                -residentialAddress: AddressDto
                -residentialAddressSameAsCorrespondenceAddress: Boolean
                -nameElements: NameElementsDto
            }

/'           note "This models an individual PSC" as Note2
             Note2 .. PscIndividualDto'/

            class PscWithIdentificationDto implements PscCommon {
                -pscCommon: PscCommonDto
                -name
                -identification:IdentificationDto
            }
            
            
           note "This models the RLE (corporate) and the \nORP (legal) types of PSC" as Note1
                Note1 -- PscWithIdentificationDto

            'PscCommonDto *-- PscIndividualDto::pscCommon
            PscCommonDto *-- PscIndividualDto::pscCommon
            PscCommonDto *-- PscWithIdentificationDto::pscCommon
            PscIndividualDto::nameElements -o NameElementsDto
            PscWithIdentificationDto::identification --o IdentificationDto
            AddressDto o- PscCommonDto::address
            PscIndividualDto::residentialAddress -o AddressDto
            Date3TupleDto o- PscIndividualDto::dateOfBirth
        }
    }

@enduml